sylius_grid:
    grids:
        setono_sylius_analytics_admin_property:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_analytics.model.property.class%"
            fields:
                trackingId:
                    type: string
                    label: setono_sylius_analytics.ui.tracking_id
                enabled:
                    type: twig
                    label: setono_sylius_analytics.ui.enabled
                    options:
                        template: "@SetonoSyliusAnalyticsPlugin/Admin/Grid/Field/enabled.html.twig"
                channels:
                    type: twig
                    label: sylius.ui.channels
                    options:
                        template: "@SetonoSyliusAnalyticsPlugin/Admin/Grid/Field/channels.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
