imports:
    - "@SetonoSyliusAnalyticsPlugin/Resources/config/grids/setono_sylius_analytics_admin_container.yaml"
    - "@SetonoSyliusAnalyticsPlugin/Resources/config/grids/setono_sylius_analytics_admin_property.yaml"
